Update run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,42 +1,57 @@
 #!/bin/bash
 # Shortcuts for common developer tasks
 
+disable_keyring() {
+   # Prevent Poetry v1.2.0 from using the Python keyring, which sometimes fails or hangs on Linux
+   # See: https://github.com/python-poetry/poetry/issues/2692#issuecomment-1235683370
+   export PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring"
+}
+
+enable_keyring() {
+   # We need to unset this for cases where the keyring is required, like publishing
+   unset PYTHON_KEYRING_BACKEND
+}
+
 # Setup the virtual environment via Poetry and install pre-commit hooks
 run_install() {
 
-   # Create and update the virtualenv
-   poetry install -v
+   # Install the poetry-plugin-export plugin, used to generate requirements.txt
+   poetry self add --quiet poetry-plugin-export
    if [ $? != 0 ]; then
+      echo "*** Failed to install Poetry plugin: poetry-plugin-export"
+      exit 1
+   fi
+
+   # Create and update the virtualenv, synchronizing it to versions in poetry.lock
+   poetry install --sync
+   if [ $? != 0 ]; then
+      echo "*** Failed to install dependencies"
       exit 1
    fi
 
    # Upgrade embedded packages within the virtualenv
    # This command sometimes returns $?=1 on Windows, even though it succeeds <sigh>
    poetry run pip install --quiet --upgrade pip wheel setuptools 2>/dev/null
-
    # Install the pre-commit hooks
    poetry run pre-commit install 
    if [ $? != 0 ]; then
+      echo "*** Failed to install pre-commit hooks"
       exit 1
    fi
 
 }
 
-
-# Activate the current Poetry virtual environment
-run_activate() {
-   echo "source "$(dirname $(poetry run which python) 2>/dev/null)/activate""
-}
-
 # Regenerate the docs/requirements.txt file
 run_requirements() {
-   poetry export --format=requirements.txt --without-hashes --dev --output=docs/requirements.txt
+   poetry export --format=requirements.txt --without-hashes --with dev --output=docs/requirements.txt
    if [ $? != 0 ]; then
+      echo "*** Failed to export requirements.txt"
       exit 1
    fi
 
    poetry run python utils/dos2unix.py docs/requirements.txt
    if [ $? != 0 ]; then
+      echo "*** Failed to convert requirements.txt to UNIX line endings"
       exit 1
    fi
 }
@@ -332,9 +347,6 @@ case $1 in
    install|setup)
       run_install
       ;;
-   activate)
-      run_activate
-      ;;
    requirements)
       run_requirements
       ;;
@@ -381,7 +393,9 @@ case $1 in
       run_release $*
       ;;
    publish)
+      enable_keyring
       run_publish
+      disable_keyring
       ;;
    *)
       echo ""
@@ -392,7 +406,6 @@ case $1 in
       echo "Usage: run <command>"  
       echo ""
       echo "- run install: Setup the virtualenv via Poetry and install pre-commit hooks"
-      echo "- run activate: Print command needed to activate the Poetry virtualenv"
       echo "- run requirements: Regenerate the docs/requirements.txt file"
       echo "- run diagnostics: Print diagnostics about the Cedar Backup runtime environment"
       echo "- run format: Run the code formatters"
