Rework the Sphinx to better support readthedocs.io

diff --git a/run b/run
--- a/run
+++ b/run
@@ -92,6 +92,37 @@ run_tox() {
    poetry run tox -c .toxrc -e "precommit,{py}-{coverage,nocoverage}"
 }
 
+# Build the Sphinx documentation for apologies.readthedocs.io
+run_docs() {
+   open="no"
+
+   while getopts ":o" option; do
+     case $option in
+       o)
+         open="yes"
+         ;;
+       ?)
+         echo "invalid option -$OPTARG"
+         exit 1
+         ;;
+     esac
+   done
+
+   poetry run which sphinx-build > /dev/null
+   if [ $? != 0 ]; then
+      run_install
+   fi
+
+   cd docs
+   poetry run sphinx-build -b html -d _build/doctrees . _build/html 2>&1 | \
+         grep -v "WARNING: document isn't included in any toctree" | \
+         grep -v "WARNING: more than one target found for cross-reference"
+
+   if [ $open == "yes" ]; then
+      $(which start || which open) _build/html/index.html 2>/dev/null  # start on Windows, open on MacOS
+   fi
+}
+
 # Tag the current code and publish to PyPI
 # Before doing this, you must retrieve and configure a local API token
 # For instance: poetry config pypi-token.pypi token --local
@@ -143,6 +174,10 @@ case $1 in
    tox)
       run_tox
       ;;
+   doc*)
+      shift 1
+      run_docs $*
+      ;;
    publish)
       run_publish
       ;;
@@ -162,6 +197,8 @@ case $1 in
       echo "- run test -c: Run the unit tests with coverage"
       echo "- run test -ch: Run the unit tests with coverage and open the HTML report"
       echo "- run tox: Run the broader Tox test suite used by the GitHub CI action"
+      echo "- run docs: Build the Spinx documentation for cedar-backup3.readthedocs.io"
+      echo "- run docs -o: Build the Spinx documentation and open in a browser"
       echo "- run publish: Tag the current code and publish to PyPI"
       echo ""
       exit 1
